DROP TABLE IF EXISTS user_account;
DROP TABLE IF EXISTS timer;
DROP TABLE IF EXISTS timer_group;

CREATE TABLE IF NOT EXISTS public.user_account
(
    user_account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    PRIMARY KEY (user_account_id),
    UNIQUE (name),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.timer_group
(
    timer_group_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY (timer_group_id)
);

CREATE TABLE IF NOT EXISTS public.timer
(
    timer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    seconds integer NOT NULL,
    timer_group_id integer NOT NULL,
    PRIMARY KEY (timer_id)
);

ALTER TABLE IF EXISTS public.timer
    ADD FOREIGN KEY (timer_group_id)
    REFERENCES public.timer_group (timer_group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

INSERT INTO timer_group (timer_group_id, name)
VALUES
(1,'ESP1'),
(2,'PRESENTACIÓN ISOFT')
ON CONFLICT DO NOTHING;

INSERT INTO timer (timer_id, name, seconds, timer_group_id)
VALUES
(1, 'Intro', 5, 1),
(2, 'Objetivo', 5, 1),
(3, 'Tema1', 300, 1),
(4, 'Intro', 5, 2)
ON CONFLICT DO NOTHING;
